# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
