# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articles_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='comments',
            field=models.PositiveIntegerField(default=0, verbose_name='评论量'),
        ),
    ]
