# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-08 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180408_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
