# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180408_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
