# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0006_auto_20180409_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='collects',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
