# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articles_collects'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
