# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_articles_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='pdf',
        ),
    ]
