# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20180419_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='abstract',
            field=models.TextField(blank=True, max_length=1000, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(null=True, verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='collects',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='收藏人'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=300, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='artid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='article.Articles', verbose_name='评论文章'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='commentsreply',
            name='art_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_article', to='article.Articles', verbose_name='回复文章'),
        ),
        migrations.AlterField(
            model_name='commentsreply',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reply', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='commentsreply',
            name='author_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to=settings.AUTH_USER_MODEL, verbose_name='回复给'),
        ),
        migrations.AlterField(
            model_name='commentsreply',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='article.Comments', verbose_name='回复评论'),
        ),
        migrations.AlterField(
            model_name='commentsreply',
            name='content',
            field=models.TextField(verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='commentsreply',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='born',
            field=models.DateField(default='1990-1-1', verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('N', '保密')], default='N', max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
