# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20180424_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel', models.ImageField(upload_to='carousel/', verbose_name='轮播图')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图管理',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-created_time',), 'verbose_name': '文章管理', 'verbose_name_plural': '文章管理'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '标签管理', 'verbose_name_plural': '标签管理'},
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name': '学院管理', 'verbose_name_plural': '学院管理'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-submit_date',), 'verbose_name': '评论管理', 'verbose_name_plural': '评论管理'},
        ),
        migrations.AlterModelOptions(
            name='commentsreply',
            options={'ordering': ('submit_date',), 'verbose_name': '回复管理', 'verbose_name_plural': '回复管理'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'ordering': ('-created_time',), 'verbose_name': '个人信息管理', 'verbose_name_plural': '个人信息管理'},
        ),
    ]
